"""
Python module with some utility functions
"""

import os
import json
import pickle
import numpy as np
import pandas as pd
import time
from typing import Union, List

def get_current_time() -> str:
    """
    This function returns the current time in the format 'dd-mm-YYYY_HH-MM-SS'.
    It is used to produce the name of the files saved

    Returns:
        current_time: string representing the current time

    """

    t = time.localtime()
    current_time = time.strftime("%d-%m-%Y_%H-%M-%S", t)
    return current_time


def get_most_recent_file(directory_path: str, file_pos: int = 0) -> str:
    """
    Function to get the most recent file (i.e. last modified file) in a directory path.

    Args:
        directory_path: Directory path where the files are stored
        file_pos (int): position of the file to retrieve, by default is 0 (most recent file), file_pos=1 will retrieve the second most recent file and so on

    Returns:
        Path to the most recent file in the directory path

    """

    # NOTE: Insert here only the files contained in directory_path, do
    # not consider subdirectories
    files_list = [
        x
        for x in os.listdir(directory_path)
        if os.path.isfile(os.path.join(directory_path, x))
    ]

    files = sorted(
        files_list,
        key=lambda x: os.path.getmtime(os.path.join(directory_path, x)),
        reverse=True,
    )

    return os.path.join(directory_path, files[file_pos])


def save_element(
    element: list,
    directory_path: str,
    filename: str = "",
    filetype: str = "pickle",
    add_time: bool = True,
) -> None:
    """
    Function to save an element produced by an experiment in a file (i.e. `npz` or `pickle` file) in the specified directory path.

    Args:
        element: Element to be saved
        directory_path: Directory path where the file will be saved
        filename: Name of the file
        filetype: Type of the file (i.e. `npz` or `pickle`)
        add_time: boolean flag to see weather to add the current time to the filename

    Returns:
        The method saves element and does not return any value
    """

    filetypes = ["pickle", "npz", "csv.gz", "json"]

    assert filetype in filetypes, f"filetype must be one of {filetypes}"

    if add_time:
        current_time = get_current_time()
        filename = current_time + "_" + filename

    path = directory_path + "/" + filename

    if filetype == "pickle":
        with open(path + ".pickle", "wb") as fl:
            pickle.dump(element, fl)
    elif filetype == "npz":
        np.savez(path, element=element)
    elif filetype == "csv.gz":
        element.to_csv(path + ".csv.gz", index=False, compression="gzip")
    elif filetype == "json":
        with open(path, "w") as fl:
            json.dump(element, fl, indent=4)

def generate_path(basepath: str = os.getcwd(), folders: List[str] = []) -> str:
    """
    Generate a path starting from a basepath and a list of folders to join to the basepath.

    Args:
        basepath: The basepath from which to start to generate the path, by default os.getcwd()
        folders: A list of strings containing the ordered list of subfolders to join to the basepath, by default []
    Returns:
        path: The path generated by joining the basepath and the folders
    """

    # Verify weather basepath is a valid path in the system
    assert os.path.exists(basepath), f"Basepath {basepath} does not exist"

    path = basepath + "/"

    # Join the basepath with the folders
    for folder in folders:
        path = os.path.join(path, folder) + "/"
        # Verify weather the path exists or not
        if not os.path.exists(path):
            os.makedirs(path)

    return path[:-1]
